#! /usr/bin/env bash

source /infra/utils

set -e
set -u
set -x

cd $TARGET
DIR=$(setup_dir)

# TBD: unify on test or tests
# TBD: needs setup.py infra
# python setup.py test -t test* -i ${OMERO_DIST}/etc/ice.config -v

# Import test data
./.omeroci/test-data

set +u
export DJANGO_SETTINGS_MODULE=omeroweb.settings
export OMERODIR=/opt/omero/web/OMERO.web
export ICE_CONFIG=${OMERO_DIST}/etc/ice.config
pytest -v
